export const getRequestConfig = (payload: { session: string }) => {
  const { session } = payload;
  return {
    headers: {
      Authorization: `Bearer ${session}`,
      "Content-Type": "application/json",
    },
  };
};

export const regionProvinceMap = {
  "Region I - Ilocos Region": [
    "Ilocos Norte",
    "Ilocos Sur",
    "La Union",
    "Pangasinan",
  ],
  "Region II - Cagayan Valley": [
    "Batanes",
    "Cagayan",
    "Isabela",
    "Nueva Vizcaya",
    "Quirino",
  ],
  "Region III - Central Luzon": [
    "Aurora",
    "Bataan",
    "Bulacan",
    "Nueva Ecija",
    "Pampanga",
    "Tarlac",
    "Zambales",
  ],
  "Region IV-A - CALABARZON": [
    "Cavite",
    "Laguna",
    "Batangas",
    "Rizal",
    "Quezon",
  ],
  "MIMAROPA Region": [
    "Occidental Mindoro",
    "Oriental Mindoro",
    "Marinduque",
    "Romblon",
    "Palawan",
  ],
  "Region V - Bicol Region": [
    "Albay",
    "Camarines Norte",
    "Camarines Sur",
    "Catanduanes",
    "Masbate",
    "Sorsogon",
  ],
  "Region VI - Western Visayas": [
    "Aklan",
    "Antique",
    "Capiz",
    "Guimaras",
    "Iloilo",
    "Negros Occidental",
  ],
  "Region VII - Central Visayas": [
    "Bohol",
    "Cebu",
    "Negros Oriental",
    "Siquijor",
  ],
  "Region VIII - Eastern Visayas": [
    "Biliran",
    "Eastern Samar",
    "Leyte",
    "Northern Samar",
    "Samar",
    "Southern Leyte",
  ],
  "Region IX - Zamboanga Peninsula": [
    "Zamboanga del Norte",
    "Zamboanga del Sur",
    "Zamboanga Sibugay",
  ],
  "Region X - Northern Mindanao": [
    "Bukidnon",
    "Camiguin",
    "Lanao del Norte",
    "Misamis Occidental",
    "Misamis Oriental",
  ],
  "Region XI - Davao Region": [
    "Davao de Oro",
    "Davao del Norte",
    "Davao del Sur",
    "Davao Occidental",
    "Davao Oriental",
  ],
  "Region XII - SOCCSKSARGEN": [
    "Cotabato",
    "Sarangani",
    "South Cotabato",
    "Sultan Kudarat",
  ],
  "Region XIII - Caraga": [
    "Agusan del Norte",
    "Agusan del Sur",
    "Dinagat Islands",
    "Surigao del Norte",
    "Surigao del Sur",
  ],
  "NCR - National Capital Region": ["Metro Manila"],
  "CAR - Cordillera Administrative Region": [
    "Abra",
    "Apayao",
    "Benguet",
    "Ifugao",
    "Kalinga",
    "Mountain Province",
  ],
  "BARMM - Bangsamoro Autonomous Region in Muslim Mindanao": [
    "Basilan",
    "Lanao del Sur",
    "Maguindanao del Norte",
    "Maguindanao del Sur",
    "Sulu",
    "Tawi-Tawi",
  ],
};

export const provinceAndCities = {
  "Ilocos Norte": [
    "Adams",
    "Bacarra",
    "Badoc",
    "Bangui",
    "Banna",
    "Burgos",
    "Carasi",
    "Currimao",
    "Dingras",
    "Dumalneg",
    "Laoag City",
    "Marcos",
    "Nueva Era",
    "Pagudpud",
    "Paoay",
    "Pasuquin",
    "Piddig",
    "Pinili",
    "San Nicolas",
    "Sarrat",
    "Solsona",
    "Vintar",
    "Batac City",
  ],
  "Ilocos Sur": [
    "Alilem",
    "Banayoyo",
    "Bantay",
    "Burgos",
    "Cabugao",
    "Candon City",
    "Caoayan",
    "Cervantes",
    "Galimuyod",
    "Gregorio del Pilar",
    "Lidlidda",
    "Magsingal",
    "Nagbukel",
    "Narvacan",
    "Quirino",
    "Salcedo",
    "San Emilio",
    "San Esteban",
    "San Ildefonso",
    "San Juan",
    "San Vicente",
    "Santa",
    "Santa Catalina",
    "Santa Cruz",
    "Santa Lucia",
    "Santa Maria",
    "Santiago",
    "Santo Domingo",
    "Sigay",
    "Sinait",
    "Sugpon",
    "Suyo",
    "Tagudin",
    "Vigan City",
  ],
  "La Union": [
    "Agoo",
    "Aringay",
    "Bacnotan",
    "Bagulin",
    "Balaoan",
    "Bangar",
    "Bauang",
    "Burgos",
    "Caba",
    "Luna",
    "Naguilian",
    "Pugo",
    "Rosario",
    "San Fernando City",
    "San Gabriel",
    "San Juan",
    "Santo Tomas",
    "Santol",
    "Sudipen",
    "Tubao",
  ],
  Pangasinan: [
    "Agno",
    "Aguilar",
    "Alaminos City",
    "Alcala",
    "Anda",
    "Asingan",
    "Balungao",
    "Bani",
    "Basista",
    "Bautista",
    "Bayambang",
    "Binalonan",
    "Binmaley",
    "Bolinao",
    "Bugallon",
    "Burgos",
    "Calasiao",
    "Dagupan City",
    "Dasol",
    "Infanta",
    "Labrador",
    "Laoac",
    "Lingayen",
    "Mabini",
    "Malasiqui",
    "Manaoag",
    "Mangaldan",
    "Mangatarem",
    "Mapandan",
    "Natividad",
    "Pozorrubio",
    "Rosales",
    "San Carlos City",
    "San Fabian",
    "San Jacinto",
    "San Manuel",
    "San Nicolas",
    "San Quintin",
    "Santa Barbara",
    "Santa Maria",
    "Santo Tomas",
    "Sison",
    "Sual",
    "Tayug",
    "Umingan",
    "Urbiztondo",
    "Urdaneta City",
    "Villasis",
  ],
  Batanes: ["Basco", "Itbayat", "Ivana", "Mahatao", "Sabtang", "Uyugan"],
  Cagayan: [
    "Abulug",
    "Alcala",
    "Allacapan",
    "Amulung",
    "Aparri",
    "Baggao",
    "Ballesteros",
    "Buguey",
    "Calayan",
    "Camalaniugan",
    "Claveria",
    "Enrile",
    "Gattaran",
    "Gonzaga",
    "Iguig",
    "Lal-lo",
    "Lasam",
    "Pamplona",
    "Peñablanca",
    "Piat",
    "Rizal",
    "Sanchez-Mira",
    "Santa Ana",
    "Santa Praxedes",
    "Santa Teresita",
    "Santo Niño",
    "Solana",
    "Tuao",
    "Tuguegarao City",
  ],
  Isabela: [
    "Alicia",
    "Angadanan",
    "Aurora",
    "Benito Soliven",
    "Burgos",
    "Cabagan",
    "Cabatuan",
    "Cordon",
    "Delfin Albano",
    "Dinapigue",
    "Divilacan",
    "Echague",
    "Gamu",
    "Ilagan City",
    "Jones",
    "Luna",
    "Maconacon",
    "Mallig",
    "Naguilian",
    "Palanan",
    "Quezon",
    "Quirino",
    "Ramon",
    "Reina Mercedes",
    "Roxas",
    "San Agustin",
    "San Guillermo",
    "San Isidro",
    "San Manuel",
    "San Mariano",
    "San Mateo",
    "San Pablo",
    "Santa Maria",
    "Santo Tomas",
    "Santiago City",
    "Tumauini",
  ],
  "Nueva Vizcaya": [
    "Alfonso Castañeda",
    "Ambaguio",
    "Aritao",
    "Bagabag",
    "Bambang",
    "Bayombong",
    "Diadi",
    "Dupax del Norte",
    "Dupax del Sur",
    "Kasibu",
    "Kayapa",
    "Quezon",
    "Santa Fe",
    "Solano",
    "Villaverde",
  ],
  Quirino: [
    "Aglipay",
    "Cabarroguis",
    "Diffun",
    "Maddela",
    "Nagtipunan",
    "Saguday",
  ],
  Aurora: [
    "Baler",
    "Casiguran",
    "Dilasag",
    "Dinalungan",
    "Dingalan",
    "Dipaculao",
    "Maria Aurora",
    "San Luis",
  ],
  Bataan: [
    "Balanga City",
    "Abucay",
    "Bagac",
    "Dinalupihan",
    "Hermosa",
    "Limay",
    "Mariveles",
    "Morong",
    "Orani",
    "Orion",
    "Pilar",
    "Samal",
  ],
  Bulacan: [
    "Baliwag City",
    "Malolos City",
    "Meycauayan City",
    "San Jose del Monte City",
    "Angat",
    "Balagtas",
    "Bocaue",
    "Bulakan",
    "Bustos",
    "Calumpit",
    "Doña Remedios Trinidad",
    "Guiguinto",
    "Hagonoy",
    "Marilao",
    "Norzagaray",
    "Obando",
    "Pandi",
    "Paombong",
    "Plaridel",
    "Pulilan",
    "San Ildefonso",
    "San Miguel",
    "San Rafael",
    "Santa Maria",
  ],
  "Nueva Ecija": [
    "Cabanatuan City",
    "Gapan City",
    "Muñoz City",
    "Palayan City",
    "Aliaga",
    "Bongabon",
    "Cabiao",
    "Carranglan",
    "Cuyapo",
    "Gabaldon",
    "General Mamerto Natividad",
    "General Tinio",
    "Guimba",
    "Jaen",
    "Laur",
    "Licab",
    "Llanera",
    "Lupao",
    "Nampicuan",
    "Pantabangan",
    "Peñaranda",
    "Quezon",
    "Rizal",
    "San Antonio",
    "San Isidro",
    "San Leonardo",
    "Santa Rosa",
    "Santo Domingo",
    "Talavera",
    "Talugtug",
    "Zaragoza",
  ],
  Pampanga: [
    "Angeles City",
    "San Fernando City",
    "Apalit",
    "Arayat",
    "Bacolor",
    "Candaba",
    "Floridablanca",
    "Guagua",
    "Lubao",
    "Mabalacat",
    "Macabebe",
    "Magalang",
    "Masantol",
    "Mexico",
    "Minalin",
    "Porac",
    "San Luis",
    "San Simon",
    "Santa Ana",
    "Santa Rita",
    "Santo Tomas",
    "Sasmuan",
  ],
  Tarlac: [
    "Tarlac City",
    "Anao",
    "Bamban",
    "Camiling",
    "Capas",
    "Concepcion",
    "Gerona",
    "La Paz",
    "Mayantoc",
    "Moncada",
    "Paniqui",
    "Pura",
    "Ramos",
    "San Clemente",
    "San Jose",
    "San Manuel",
    "Santa Ignacia",
    "Victoria",
  ],
  Zambales: [
    "Olongapo City",
    "Botolan",
    "Cabangan",
    "Candelaria",
    "Castillejos",
    "Iba",
    "Masinloc",
    "Palauig",
    "San Antonio",
    "San Felipe",
    "San Marcelino",
    "San Narciso",
    "Santa Cruz",
    "Subic",
  ],
  Cavite: [
    "Alfonso",
    "Amadeo",
    "Bacoor City",
    "Carmona",
    "Cavite City",
    "Dasmariñas City",
    "General Emilio Aguinaldo",
    "General Mariano Alvarez",
    "General Trias City",
    "Imus City",
    "Indang",
    "Kawit",
    "Magallanes",
    "Maragondon",
    "Mendez",
    "Naic",
    "Noveleta",
    "Rosario",
    "Silang",
    "Tagaytay City",
    "Tanza",
    "Ternate",
    "Trece Martires City",
  ],
  Laguna: [
    "Alaminos",
    "Bay",
    "Biñan City",
    "Cabuyao City",
    "Calamba City",
    "Calauan",
    "Cavinti",
    "Famy",
    "Kalayaan",
    "Liliw",
    "Los Baños",
    "Luisiana",
    "Lumban",
    "Mabitac",
    "Magdalena",
    "Majayjay",
    "Nagcarlan",
    "Paete",
    "Pagsanjan",
    "Pakil",
    "Pangil",
    "Pila",
    "Rizal",
    "San Pablo City",
    "San Pedro City",
    "Santa Cruz",
    "Santa Maria",
    "Santa Rosa City",
    "Siniloan",
    "Victoria",
  ],
  Batangas: [
    "Agoncillo",
    "Alitagtag",
    "Balayan",
    "Balete",
    "Batangas City",
    "Bauan",
    "Calaca City",
    "Calatagan",
    "Cuenca",
    "Ibaan",
    "Laurel",
    "Lemery",
    "Lian",
    "Lipa City",
    "Lobo",
    "Mabini",
    "Malvar",
    "Mataasnakahoy",
    "Nasugbu",
    "Padre Garcia",
    "Rosario",
    "San Jose",
    "San Juan",
    "San Luis",
    "San Nicolas",
    "San Pascual",
    "Santa Teresita",
    "Santo Tomas City",
    "Taal",
    "Talisay",
    "Tanauan City",
    "Taysan",
    "Tingloy",
    "Tuy",
  ],
  Rizal: [
    "Angono",
    "Antipolo City",
    "Baras",
    "Binangonan",
    "Cainta",
    "Cardona",
    "Jalajala",
    "Morong",
    "Pililla",
    "Rodriguez",
    "San Mateo",
    "Tanay",
    "Taytay",
    "Teresa",
  ],
  Quezon: [
    "Agdangan",
    "Alabat",
    "Atimonan",
    "Buenavista",
    "Burdeos",
    "Calauag",
    "Candelaria",
    "Catanauan",
    "Dolores",
    "General Luna",
    "General Nakar",
    "Guinayangan",
    "Gumaca",
    "Infanta",
    "Jomalig",
    "Lopez",
    "Lucban",
    "Lucena City",
    "Macalelon",
    "Mauban",
    "Mulanay",
    "Padre Burgos",
    "Pagbilao",
    "Panukulan",
    "Patnanungan",
    "Perez",
    "Pitogo",
    "Plaridel",
    "Polillo",
    "Quezon",
    "Real",
    "Sampaloc",
    "San Andres",
    "San Antonio",
    "San Francisco",
    "San Narciso",
    "Sariaya",
    "Tagkawayan",
    "Tayabas City",
    "Tiaong",
    "Unisan",
  ],
  "Occidental Mindoro": [
    "Abra de Ilog",
    "Calintaan",
    "Looc",
    "Lubang",
    "Magsaysay",
    "Mamburao",
    "Paluan",
    "Rizal",
    "Sablayan",
    "San Jose",
    "Santa Cruz",
  ],
  "Oriental Mindoro": [
    "Baco",
    "Bansud",
    "Bongabong",
    "Bulalacao",
    "Calapan City",
    "Gloria",
    "Mansalay",
    "Naujan",
    "Pola",
    "Pinamalayan",
    "Puerto Galera",
    "Roxas",
    "San Teodoro",
    "Victoria",
  ],
  Marinduque: [
    "Boac",
    "Buenavista",
    "Gasan",
    "Mogpog",
    "Santa Cruz",
    "Torrijos",
  ],
  Romblon: [
    "Alcantara",
    "Banton",
    "Cajidiocan",
    "Calatrava",
    "Concepcion",
    "Corcuera",
    "Ferrol",
    "Looc",
    "Magdiwang",
    "Odiongan",
    "Romblon",
    "San Agustin",
    "San Andres",
    "San Fernando",
    "San Jose",
    "Santa Fe",
    "Santa Maria",
  ],
  Palawan: [
    "Aborlan",
    "Agutaya",
    "Araceli",
    "Balabac",
    "Bataraza",
    "Brooke's Point",
    "Busuanga",
    "Cagayancillo",
    "Coron",
    "Culion",
    "Cuyo",
    "Dumaran",
    "El Nido",
    "Kalayaan",
    "Linapacan",
    "Magsaysay",
    "Narra",
    "Quezon",
    "Rizal",
    "Puerto Princesa City",
  ],
  Albay: [
    "Legazpi City",
    "Tabaco City",
    "Ligao City",
    "Santo Domingo",
    "Malilipot",
    "Malinao",
    "Bacacay",
    "Tiwi",
    "Camalig",
    "Daraga",
    "Manito",
    "Rapurapu",
    "Guinobatan",
    "Oas",
    "Jovellar",
    "Pioduran",
    "Polangui",
    "Libon",
  ],
  "Camarines Norte": [
    "Daet",
    "Jose Panganiban",
    "Labo",
    "Basud",
    "Capalonga",
    "Paracale",
    "Mercedes",
    "San Lorenzo Ruiz",
    "San Vicente",
    "Santa Elena",
    "Talisay",
  ],
  "Camarines Sur": [
    "Naga City",
    "Iriga City",
    "Baao",
    "Balatan",
    "Bato",
    "Bombon",
    "Buhi",
    "Bula",
    "Nabua",
    "Baño",
    "Bula",
    "Libmanan",
    "Milaor",
    "Minalabac",
    "Pamplona",
    "Pasacao",
    "San Fernando",
    "Gainza",
    "Libmanan",
    "Milaor",
    "Minalabac",
    "Pamplona",
    "Pasacao",
    "San Fernando",
    "Caramoan",
    "Garchitorena",
    "Goa",
    "Lagonoy",
    "Presentacion",
    "Sagnay",
    "San Jose",
    "Siruma",
    "Tigaon",
    "Tinambac",
    "Baao",
    "Balatan",
    "Bato",
    "Buhi",
    "Bula",
    "Nabua",
  ],
  Catanduanes: [
    "Virac",
    "Viga",
    "San Miguel",
    "San Andres",
    "Pandan",
    "Gigmoto",
    "Caramoran",
    "Bato",
  ],
  Masbate: [
    "Masbate City",
    "Mandaon",
    "Milagros",
    "Mobo",
    "Monreal",
    "Aroroy",
    "Baleno",
    "Balud",
    "Batuan",
    "Cataingan",
    "Cawayan",
    "Claveria",
    "Dimasalang",
    "Esperanza",
    "Pio V. Corpus",
    "Placer",
    "San Fernando",
    "Palanas",
  ],
  Sorsogon: [
    "Sorsogon City",
    "Casiguran",
    "Castilla",
    "Donsol",
    "Gubat",
    "Irosin",
    "Juban",
    "Magallanes",
    "Matnog",
    "Pilar",
    "Prieto Diaz",
    "Barcelona",
    "Bulan",
    "Bulusan",
  ],
  Aklan: [
    "Altavas",
    "Balete",
    "Banga",
    "Batan",
    "Buruanga",
    "Ibajay",
    "Kalibo",
    "Lezo",
    "Libacao",
    "Madalag",
    "Makato",
    "Malay",
    "Malinao",
    "Nabas",
    "Numancia",
    "Tangalan",
  ],
  Antique: [
    "Anini-y",
    "Barbaza",
    "Belison",
    "Bugasong",
    "Caluya",
    "Culasi",
    "Hamtic",
    "Laua-an",
    "Libertad",
    "Pandan",
    "Patnongon",
    "San Jose de Buenavista",
    "San Remigio",
    "Sebaste",
    "Sibalom",
    "Tibiao",
    "Tobias Fornier",
  ],
  Capiz: [
    "Batan",
    "Dumarao",
    "Ivisan",
    "Jamindan",
    "Maayon",
    "Mambusao",
    "Panay",
    "Pilar",
    "President Roxas",
    "Punta Tabuc",
    "Roxas City",
    "Sapian",
    "Sigma",
    "Tapaz",
  ],
  Guimaras: [
    "Buenavista",
    "Jordan",
    "Nueva Valencia",
    "San Lorenzo",
    "Sibunag",
  ],
  Iloilo: [
    "Ajuy",
    "Alimodian",
    "Anilao",
    "Badiangan",
    "Balasan",
    "Banate",
    "Barotac Nuevo",
    "Barotac Viejo",
    "Batad",
    "Bingawan",
    "Cabatuan",
    "Calinog",
    "Carles",
    "Concepcion",
    "Dingle",
    "Dueñas",
    "Dumangas",
    "Estancia",
    "Guimbal",
    "Igbaras",
    "Iloilo City",
    "Janiuay",
    "Lambunao",
    "Leganes",
    "Lemery",
    "Leon",
    "Maasin",
    "Miagao",
    "Mina",
    "New Lucena",
    "Oton",
    "Passi City",
    "Pavia",
    "Pototan",
    "San Dionisio",
    "San Enrique",
    "San Joaquin",
    "San Miguel",
    "San Rafael",
    "Santa Barbara",
    "Sara",
    "Tigbauan",
    "Tubungan",
    "Zarraga",
  ],
  "Negros Occidental": [
    "Bacolod City",
    "Bago City",
    "Binalbagan",
    "Cadiz City",
    "Cauayan",
    "Enrique B. Magalona",
    "Escalante City",
    "Himamaylan City",
    "Hinigaran",
    "Hinoba-an",
    "Ilog",
    "Isabela",
    "Kabankalan City",
    "La Castellana",
    "Manapla",
    "Murcia",
    "Pontevedra",
    "Pulupandan",
    "San Carlos City",
    "San Enrique",
    "Silay City",
    "Sipalay City",
    "Talisay City",
    "Toboso",
    "Valladolid",
    "Victorias City",
  ],
  Bohol: [
    "Tagbilaran City",
    "Danao City",
    "Panglao",
    "Carmen",
    "Catigbian",
    "Dauis",
    "Dimiao",
    "Getafe",
    "Guindulman",
    "Inabanga",
    "Jagna",
    "Loon",
    "Loboc",
    "Mabini",
    "Maribojoc",
    "Panglao",
    "Pilar",
    "Sierra Bullones",
    "Talibon",
    "Tubigon",
  ],
  Cebu: [
    "Cebu City",
    "Mandaue City",
    "Lapu-Lapu City",
    "Talisay City",
    "Carcar City",
    "Naga City",
    "Toledo City",
    "Bogo City",
    "Danao City",
    "Liloan",
    "Balamban",
    "Carmen",
    "Consolacion",
    "Cordova",
    "San Fernando",
    "Sogod",
    "Tudela",
    "Alcantara",
    "Aloguinsan",
    "Argao",
    "Asturias",
    "Badian",
    "Balamban",
    "Barili",
    "Bogo",
    "Borbon",
    "Dalaguete",
    "Dumanjug",
    "Ginatilan",
    "Lambusan",
    "Lapu-lapu City",
  ],
  "Negros Oriental": [
    "Dumaguete City",
    "Bais City",
    "Bayawan City",
    "Canlaon City",
    "Tanjay City",
    "Apolonio",
    "Bacong",
    "Basay",
    "Dauin",
    "Dumaguete City",
    "La Libertad",
    "Mabinay",
    "Manjuyod",
    "Pamplona",
    "Santa Catalina",
    "Siaton",
    "Valencia",
  ],
  Siquijor: ["Siquijor", "Larena", "San Juan", "Lazi", "Maria", "Santo Niño"],
  Biliran: [
    "Naval",
    "Almeria",
    "Biliran",
    "Cabucgayan",
    "Caibiran",
    "Culaba",
    "Kawayan",
    "Maripipi",
  ],
  "Eastern Samar": [
    "Borongan City",
    "Guiuan",
    "Lawaan",
    "Llorente",
    "Maslog",
    "Maydolong",
    "Mercedes",
    "Oras",
    "San Julian",
    "San Policarpo",
    "Sulat",
    "Taft",
  ],
  Leyte: [
    "Tacloban City",
    "Ormoc City",
    "Baybay City",
    "Maasin City",
    "Abuyog",
    "Alangalang",
    "Babatngon",
    "Barugo",
    "Bato",
    "Burauen",
    "Calubian",
    "Capoocan",
    "Carigara",
    "Dagami",
    "Dulag",
    "Hindang",
    "Inopacan",
    "Isabel",
    "Jaro",
    "Javier",
    "Julita",
    "Kananga",
    "La Paz",
    "Lapaz",
    "Leyte",
    "Libagon",
    "Liloan",
    "Mahaplag",
    "Matag-ob",
    "Palo",
    "Pastrana",
    "San Isidro",
    "San Miguel",
    "San Pablo",
    "San Sebastian",
    "Santa Fe",
    "Tabango",
    "Tanauan",
    "Tolosa",
    "Tunga",
  ],
  "Northern Samar": [
    "Catarman",
    "Calbayog City",
    "Allen",
    "Biri",
    "Bobon",
    "Capul",
    "Catubig",
    "Gamay",
    "Laoang",
    "Lapinig",
    "Las Navas",
    "Lavezares",
    "San Antonio",
    "San Isidro",
    "San Jose",
    "San Vicente",
    "Santo Niño",
    "Silvino Lobos",
    "Victoria",
  ],
  Samar: [
    "Catbalogan City",
    "Calbayog City",
    "Basey",
    "Catbalogan",
    "Marabut",
    "San Jorge",
    "San Sebastian",
    "Sta Margarita",
    "Sta Rita",
    "Talalora",
    "Pinabacdao",
    "Gandara",
    "San Sebastian",
    "Santo Niño",
  ],
  "Southern Leyte": [
    "Maasin City",
    "Sogod",
    "Bontoc",
    "San Juan",
    "Libagon",
    "Liloan",
    "Tomas Oppus",
    "Anahawan",
    "Bontoc",
    "Hinunangan",
    "Hinundayan",
    "Saint Bernard",
    "Silago",
    "San Francisco",
    "Taytay",
    "Malitbog",
  ],
  "Zamboanga del Norte": [
    "Dipolog City",
    "Dapitan City",
    "Labason",
    "Salug",
    "Sergio Osmeña Sr.",
    "Sindangan",
    "Siayan",
    "Manukan",
    "Kalawit",
    "Godod",
    "Jose Dalman",
    "Polanco",
    "Siocon",
    "Tampilisan",
    "Liloy",
    "Mahayag",
  ],
  "Zamboanga del Sur": [
    "Pagadian City",
    "Lakewood",
    "Midsalip",
    "Josefina",
    "Dumalinao",
    "Guipos",
    "Lakewood",
    "Mahayag",
    "Pitogo",
    "San Pablo",
    "Tambulig",
    "Zamboanga City",
    "Pau",
    "Pontevedra",
    "Dapitan",
  ],

  "Zamboanga Sibugay": [
    "Ipil",
    "Naga",
    "RT Lim",
    "Talusan",
    "Mabuhay",
    "Malangas",
    "Olutanga",
    "Payao",
    "Siay",
    "Talusan",
  ],
  Bukidnon: [
    "Malaybalay City",
    "Valencia City",
    "Baungon",
    "Cabanglasan",
    "Damulog",
    "Dangcagan",
    "Impasug-ong",
    "Kibawe",
    "Kitaotao",
    "Lantapan",
    "Libona",
    "Malitbog",
    "Manolo Fortich",
    "Maramag",
    "Pangantucan",
    "Quezon",
    "Sumilao",
    "Talakag",
  ],
  Camiguin: [
    "Mambajao",
    "Mahinog",
    "Guinsiliban",
    "Sagay",
    "Talisayan",
    "Catarman",
  ],
  "Lanao del Norte": [
    "Tubod",
    "Iligan City",
    "Kapatagan",
    "Lala",
    "Linamon",
    "Magsaysay",
    "Maigo",
    "Salvador",
    "Sapang Dalaga",
    "Nunungan",
    "Poona Piñol",
    "Pantar",
    "Baloi",
    "Kauswagan",
    "Baroy",
    "Bacolod",
    "Bacolod",
  ],
  "Misamis Occidental": [
    "Ozamiz City",
    "Tangub City",
    "Jimenez",
    "Plaridel",
    "Oroquieta City",
    "Sinacaban",
    "Tudela",
    "Aloran",
    "Concepcion",
    "Don Victoriano Chiongbian",
    "Lopez Jaena",
    "Panaon",
    "Baliangao",
    "Clarin",
  ],

  "Misamis Oriental": [
    "Cagayan de Oro City",
    "Gingoog City",
    "El Salvador",
    "Villanueva",
    "Tagoloan",
    "Jasaan",
    "Balingoan",
    "Claveria",
    "Concepcion",
    "Magsaysay",
    "Salay",
    "Sugbongcogon",
    "Binuangan",
    "Kinoguitan",
    "Talisayan",
    "Magsaysay",
    "Medina",
  ],
  "Davao de Oro": [
    "Nabunturan",
    "Maco",
    "Maragusan",
    "Mawab",
    "Pantukan",
    "New Bataan",
    "Laak",
    "Tigum",
  ],
  "Davao del Norte": [
    "Tagum City",
    "Davao City",
    "Panabo City",
    "Samal",
    "Braulio E. Dujali",
    "Carmen",
    "Kapalong",
    "San Isidro",
    "Sto. Tomas",
    "New Corella",
  ],
  "Davao del Sur": [
    "Digos City",
    "Matanao",
    "Hagonoy",
    "Kiblawan",
    "Magsaysay",
    "Malalag",
    "Santa Cruz",
    "Bansalan",
    "Sulop",
    "Don Marcelino",
  ],
  "Davao Occidental": [
    "Malita",
    "Davao Occidental",
    "Don Marcelino",
    "Jose Abad Santos",
    "Santiago",
    "Sipay",
    "Cabo",
  ],
  "Davao Oriental": [
    "Mati City",
    "Baganga",
    "Banaybanay",
    "Cateel",
    "Governor Generoso",
    "Manay",
    "San Isidro",
    "Tarragona",
  ],
  Cotabato: [
    "Kidapawan City",
    "Midsayap",
    "Alamada",
    "Banisilan",
    "Carmen",
    "Kabacan",
    "Libungan",
    "Matalam",
    "Mlang",
    "Pikit",
    "Pigkawayan",
    "President Roxas",
    "Tulunan",
    "Antipas",
    "Makilala",
  ],
  Sarangani: [
    "Alabel",
    "Glan",
    "Malapatan",
    "Maasim",
    "Maitum",
    "Kiamba",
    "Lebak",
  ],
  "South Cotabato": [
    "Koronadal City",
    "General Santos City",
    "Surallah",
    "Polomolok",
    "T'boli",
    "Lake Sebu",
    "Norala",
    "Banga",
    "Santo Niño",
    "Tupi",
    "Tantangan",
    "Sarangani",
  ],
  "Sultan Kudarat": [
    "Isulan",
    "Tacurong City",
    "Bagumbayan",
    "Columbio",
    "Esperanza",
    "Kalamansig",
    "Lebak",
    "Sen. Ninoy Aquino",
    "Buluan",
  ],
  "Agusan del Norte": [
    "Cabadbaran City",
    "Butuan City",
    "Jabonga",
    "Kitcharao",
    "Las Nieves",
    "Magallanes",
    "Mainit",
    "Nasipit",
    "Santiago",
    "Tubay",
  ],
  "Agusan del Sur": [
    "Bunawan",
    "Esperanza",
    "La Paz",
    "Loreto",
    "San Francisco",
    "San Luis",
    "San Mateo",
    "Santa Josefa",
    "Talacogon",
    "Trento",
    "Veruela",
    "Antique",
    "Bais",
    "La Libertad",
  ],
  "Dinagat Islands": [
    "Cagdianao",
    "Dinagat",
    "Libjo",
    "San Jose",
    "San Juan",
    "Basilisa",
  ],
  "Surigao del Norte": [
    "Surigao City",
    "Butuan City",
    "Claver",
    "Dapa",
    "Del Carmen",
    "Gigaquit",
    "Mainit",
    "Placer",
    "San Benito",
    "San Isidro",
    "San Juan",
    "Sison",
    "Tandag",
  ],
  "Surigao del Sur": [
    "Tandag City",
    "Bislig City",
    "Barobo",
    "Cagwait",
    "Cantilan",
    "Carrascal",
    "Lianga",
    "Lanuza",
    "Marihatag",
    "San Agustin",
    "San Miguel",
    "Tagbina",
    "Tago",
    "Hinatuan",
  ],
  "Metro Manila": [
    "Caloocan City",
    "Las Piñas City",
    "Makati City",
    "Malabon City",
    "Mandaluyong City",
    "Manila",
    "Marikina City",
    "Muntinlupa City",
    "Navotas City",
    "Parañaque City",
    "Pasay City",
    "Pasig City",
    "Quezon City",
    "San Juan City",
    "Taguig City",
    "Valenzuela City",
    "Pateros",
  ],
  Abra: [
    "Bangued",
    "Bucay",
    "Lagangilang",
    "Luba",
    "Manabo",
    "Peñarrubia",
    "Pidigan",
    "Pilar",
    "Sallapadan",
    "San Isidro",
    "San Juan",
    "San Quintin",
    "Tayum",
    "Tineg",
    "Villacorta",
  ],
  Apayao: ["Conner", "Flora", "Kabugao", "Luna", "Pudtol", "Sta. Marcela"],
  Benguet: [
    "Atok",
    "Bokod",
    "Itogon",
    "Kabayan",
    "Kapangan",
    "Kibungan",
    "La Trinidad",
    "Mankayan",
    "Tuba",
    "Tublay",
  ],
  Ifugao: [
    "Alfonso Lista",
    "Asipulo",
    "Aurora",
    "Hungduan",
    "Kiangan",
    "Natonin",
    "Mayoyao",
    "Puguis",
    "Sabangan",
    "Sadsadan",
  ],
  Kalinga: [
    "Balbalan",
    "Conner",
    "Lubuagan",
    "Pasil",
    "Pinukpuk",
    "Tabuk City",
    "Tanudan",
    "Tinglayan",
  ],
  "Mountain Province": [
    "Bauko",
    "Besao",
    "Bontoc",
    "Natonin",
    "Sabangan",
    "Sadanga",
    "Sagada",
    "Tadian",
  ],
};

export const philippineRegions = [
  "Region I - Ilocos Region",
  "Region II - Cagayan Valley",
  "Region III - Central Luzon",
  "Region IV-A - CALABARZON",
  "MIMAROPA Region",
  "Region V - Bicol Region",
  "Region VI - Western Visayas",
  "Region VII - Central Visayas",
  "Region VIII - Eastern Visayas",
  "Region IX - Zamboanga Peninsula",
  "Region X - Northern Mindanao",
  "Region XI - Davao Region",
  "Region XII - SOCCSKSARGEN",
  "Region XIII - Caraga",
  "NCR - National Capital Region",
  "CAR - Cordillera Administrative Region",
  "BARMM - Bangsamoro Autonomous Region in Muslim Mindanao",
];

export const getTodayAndTomorrowRange = () => {
  const now = new Date();

  const startOfToday = new Date(
    now.getFullYear(),
    now.getMonth(),
    now.getDate(),
    0,
    0,
    0,
    0,
  );
  const startOfTomorrow = new Date(
    now.getFullYear(),
    now.getMonth(),
    now.getDate() + 1,
    0,
    0,
    0,
    0,
  );

  return {
    begin: startOfToday.toISOString(),
    end: startOfTomorrow.toISOString(),
  };
};

export const getCurrentMonthStartAndEnd = () => {
  const today = new Date();
  const firstDay = new Date(today.getFullYear(), today.getMonth(), 1);
  const lastDay = new Date(today.getFullYear(), today.getMonth() + 1, 0);

  return {
    begin: firstDay.toISOString(),
    end: lastDay.toISOString(),
  };
};

function getFileImage(file: File) {
  return new Promise<HTMLImageElement>((resolve, reject) => {
    const reader = new FileReader();
    reader.readAsDataURL(file);
    reader.onload = () => {
      const img = new Image();
      img.onload = () => {
        resolve(img);
      };
      img.src = reader.result as any;
    };
    reader.onerror = (error) => reject(error);
  });
}

export async function changeImage(file: any, width?: any, height?: any) {
  const image = await getFileImage(file);

  const canvas = document.createElement("canvas");

  if (width == null && height == null) {
    canvas.width = image.width;
    canvas.height = image.height;
  }

  console.log(canvas.width, canvas.height);
  const ctx = canvas.getContext("2d");
  if (ctx == null) {
    return;
  }
  ctx.drawImage(image, 0, 0, canvas.width, canvas.height);

  const base64 = canvas.toDataURL("image/webp");
  // console.log(base64, '99999')
  // const [, imageBase64] = base64.split(",");

  return base64;
}
