CREATE TYPE "public"."eaccounttype" AS ENUM('customer', 'admin');--> statement-breakpoint
CREATE TYPE "public"."ecategorytype" AS ENUM('bags', 'shoes', 'clothes', 'jewelry', 'watches', 'others');--> statement-breakpoint
CREATE TYPE "public"."eoriginsite" AS ENUM('facebook', 'shoppee', 'chicberry');--> statement-breakpoint
CREATE TYPE "public"."estatustype" AS ENUM('pending', 'ondelivery', 'success');--> statement-breakpoint
CREATE TABLE "ordertable" (
	"id" serial PRIMARY KEY NOT NULL,
	"orderid" varchar(255) NOT NULL,
	"productid" integer NOT NULL,
	"username" varchar(255),
	"price" numeric(10, 2) NOT NULL,
	"cost" numeric(10, 2) NOT NULL,
	"orderquantity" integer NOT NULL,
	"orderdate" timestamp,
	"quantityxxs" integer NOT NULL,
	"quantityxs" integer NOT NULL,
	"quantitys" integer NOT NULL,
	"quantitym" integer NOT NULL,
	"quantityl" integer NOT NULL,
	"quantityxl" integer NOT NULL,
	"quantityxxl" integer NOT NULL,
	"quantity5" integer NOT NULL,
	"quantity55" integer NOT NULL,
	"quantity6" integer NOT NULL,
	"quantity65" integer NOT NULL,
	"quantity7" integer NOT NULL,
	"quantity75" integer NOT NULL,
	"quantity8" integer NOT NULL,
	"quantity85" integer NOT NULL,
	"quantity9" integer NOT NULL,
	"quantity95" integer NOT NULL,
	"quantity100" integer NOT NULL,
	"quantity105" integer NOT NULL,
	"quantity110" integer NOT NULL,
	"quantity115" integer NOT NULL,
	"quantity120" integer NOT NULL,
	"quantitydefault" integer NOT NULL
);
--> statement-breakpoint
CREATE TABLE "orderusertable" (
	"id" serial PRIMARY KEY NOT NULL,
	"orderid" varchar(255) NOT NULL,
	"username" varchar(255),
	"receiverfirstname" varchar(255),
	"receiverlastname" varchar(255),
	"receivermobile" varchar(11),
	"region" varchar(255),
	"municity" varchar(255),
	"barangay" varchar(255),
	"address" varchar(255),
	"estatustype" "estatustype",
	"eoriginsite" "eoriginsite",
	"downpayment" numeric(10, 2),
	"totalcost" numeric(10, 2),
	"orderdate" timestamp NOT NULL
);
--> statement-breakpoint
CREATE TABLE "producttable" (
	"id" serial PRIMARY KEY NOT NULL,
	"productid" serial NOT NULL,
	"title" varchar(255) NOT NULL,
	"price" numeric(10, 2) NOT NULL,
	"cost" numeric(10, 2) NOT NULL,
	"image" varchar(255),
	"imageone" varchar(255),
	"imagetwo" varchar(255),
	"imagethree" varchar(255),
	"ecategorytype" "ecategorytype" DEFAULT 'others' NOT NULL,
	"description" text,
	"searchtag" text,
	"orders" integer NOT NULL,
	"successorders" integer NOT NULL,
	"pendingorders" integer NOT NULL,
	"quantityxxs" integer NOT NULL,
	"quantityxs" integer NOT NULL,
	"quantitys" integer NOT NULL,
	"quantitym" integer NOT NULL,
	"quantityl" integer NOT NULL,
	"quantityxl" integer NOT NULL,
	"quantityxxl" integer NOT NULL,
	"quantity5" integer NOT NULL,
	"quantity55" integer NOT NULL,
	"quantity6" integer NOT NULL,
	"quantity65" integer NOT NULL,
	"quantity7" integer NOT NULL,
	"quantity75" integer NOT NULL,
	"quantity8" integer NOT NULL,
	"quantity85" integer NOT NULL,
	"quantity9" integer NOT NULL,
	"quantity95" integer NOT NULL,
	"quantity100" integer NOT NULL,
	"quantity105" integer NOT NULL,
	"quantity110" integer NOT NULL,
	"quantity115" integer NOT NULL,
	"quantity120" integer NOT NULL,
	"quantitydefault" integer NOT NULL,
	"regdate" timestamp NOT NULL,
	CONSTRAINT "producttable_productid_unique" UNIQUE("productid")
);
--> statement-breakpoint
CREATE TABLE "usertable" (
	"id" serial PRIMARY KEY NOT NULL,
	"userid" serial NOT NULL,
	"firstname" varchar(255) NOT NULL,
	"middlename" varchar(255) NOT NULL,
	"lastname" varchar(255) NOT NULL,
	"username" varchar(255) NOT NULL,
	"password" varchar(255) NOT NULL,
	"salt" char(5) DEFAULT '' NOT NULL,
	"mobile" varchar(11) NOT NULL,
	"email" varchar(255) NOT NULL,
	"token" varchar(100) DEFAULT '' NOT NULL,
	"eaccounttype" "eaccounttype" DEFAULT 'customer',
	"regdate" timestamp NOT NULL,
	"lastdate" timestamp NOT NULL,
	"lastip" varchar(255),
	"lastdevice" varchar(255),
	"lastlocation" varchar(255),
	CONSTRAINT "usertable_userid_unique" UNIQUE("userid"),
	CONSTRAINT "usertable_username_unique" UNIQUE("username"),
	CONSTRAINT "usertable_email_unique" UNIQUE("email")
);
