CREATE TABLE "replenishmenttable" (
	"id" serial PRIMARY KEY NOT NULL,
	"expenseid" varchar(255) NOT NULL,
	"productid" serial NOT NULL,
	"expense" numeric(10, 2),
	"quantityxxs" integer NOT NULL,
	"quantityxs" integer NOT NULL,
	"quantitys" integer NOT NULL,
	"quantitym" integer NOT NULL,
	"quantityl" integer NOT NULL,
	"quantityxl" integer NOT NULL,
	"quantityxxl" integer NOT NULL,
	"quantity5" integer NOT NULL,
	"quantity55" integer NOT NULL,
	"quantity6" integer NOT NULL,
	"quantity65" integer NOT NULL,
	"quantity7" integer NOT NULL,
	"quantity75" integer NOT NULL,
	"quantity8" integer NOT NULL,
	"quantity85" integer NOT NULL,
	"quantity9" integer NOT NULL,
	"quantity95" integer NOT NULL,
	"quantity100" integer NOT NULL,
	"quantity105" integer NOT NULL,
	"quantity110" integer NOT NULL,
	"quantity115" integer NOT NULL,
	"quantity120" integer NOT NULL,
	"quantitydefault" integer NOT NULL,
	"expensedate" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "replenishmenttable_productid_unique" UNIQUE("productid")
);
